FROM node:18-alpine

WORKDIR /app
COPY . .

RUN npm install -g nx
RUN npm install
RUN npm run buildFront

# Переходим в папку Next.js
WORKDIR /app/dist/apps/front

EXPOSE 3000
CMD ["npx", "next", "start"]
