FROM node:18-alpine

WORKDIR /app

# Копируем всё, включая Nx-монорепу
COPY . .

# Устанавливаем зависимости
RUN npm install -g nx
RUN npm install

# Строим проект через NX, он сам вызовет webpack с NxAppWebpackPlugin
RUN npx nx build back --configuration=production


# Переход в собранный дистрибутив
WORKDIR /app/dist/apps/back
EXPOSE 3001
CMD ["node", "main.js"]
